import { pageIds } from "./pageIds";

const WRESTLING_SINGLETON_TYPES = [
  pageIds.WRESTLING_HOME_PAGE,
  pageIds.WRESTLING_ABOUT_PAGE,
  pageIds.WRESTLING_GALLERY_PAGE,
  pageIds.WRESTLING_MATCHES_PAGE,
  pageIds.WRESTLING_EVENTS_PAGE,
  pageIds.WRESTLING_SITE_SETTINGS_PAGE,
  pageIds.ROOT_SITE_SETTINGS_PAGE,
];

const ROOT_SINGLETON_TYPES = [
  pageIds.ROOT_SITE_SETTINGS_PAGE,
];

const STREAMING_SINGLETON_TYPES = [
  pageIds.STREAMING_SCHEDULE_PAGE,
  pageIds.STREAMING_SITE_SETTINGS_PAGE,
];

export const SINGLETON_TYPES = [
  ...WRESTLING_SINGLETON_TYPES,
  ...STREAMING_SINGLETON_TYPES,
  ...ROOT_SINGLETON_TYPES
];
